# tensorboard --logdir=runs --samples_per_plugin=images=10000000

Others:
  load_path: '../checkpoints/ddpm_anime.pth'
  save_path: '../checkpoints/'

Dataset:
  name: 'anime-faces' # 'anime-faces' or 'mnist'
  hw: 64              # 64 or 28
  batch_size: 6

LinearNoiseScheduler:
  _target_: "main.LinearNoiseScheduler"
  
  beta_start: 0.0001
  beta_end: 0.02
  num_timesteps: 1000
  device: 'cuda'

UNet:
  _target_: "main.UNet"
  
  device: 'cuda'
  im_channels: 3    # 这里记得改, 如果换数据集的话
  temb_dim: 16
  
  down_channels: [32, 64, 128, 256]
  down_sample: [true, true, true, false]
  mid_channels: [512, 512, 512, 512]

  num_heads: 4
  num_down_layers: 4
  num_mid_layers: 4
  num_up_layers: 4

Train:
  lr: 1e-5
  epochs: 100

Eval:
  sample_num: 4
  t_end: 1000